language: php
php:
    - 5.5
    - 5.6
    - 7.0

sudo: false
cache:
    directories:
        - $HOME/.composer/cache
matrix:
    fast_finish: true
    
env:
    - SYMFONY_VERSION=2.6.*
    - SYMFONY_VERSION=2.8.*
    - SYMFONY_VERSION=3.0.*
    
    
before_script:
    - composer self-update
    - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
    - php composer.phar --prefer-source install -o
    
script:
    - phpunit

